# Generated by Django 2.2 on 2023-09-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='user_name',
            new_name='username',
        ),
    ]
