# Generated by Django 4.2.5 on 2023-10-04 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_logn_regs_delete_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logn',
            old_name='username',
            new_name='user_name',
        ),
    ]
