# Generated by Django 4.2.5 on 2023-10-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_logn'),
    ]

    operations = [
        migrations.AddField(
            model_name='regs',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
